# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/XILINX/homework/2014_2_artix7_sources/tutorial/tutorial_basys3.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_xup_inv_0_1/design_1_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_1 || ORIG_REF_NAME==design_1_xup_inv_0_1}]

# IP: bd/design_1/ip/design_1_xup_and2_0_1/design_1_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_1 || ORIG_REF_NAME==design_1_xup_and2_0_1}]

# IP: bd/design_1/ip/design_1_xup_and2_0_2/design_1_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_2 || ORIG_REF_NAME==design_1_xup_and2_0_2}]

# IP: bd/design_1/ip/design_1_xup_inv_0_2/design_1_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_2 || ORIG_REF_NAME==design_1_xup_inv_0_2}]

# IP: bd/design_1/ip/design_1_xup_or2_0_1/design_1_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_0_1 || ORIG_REF_NAME==design_1_xup_or2_0_1}]

# XDC: bd/design_1/design_1_ooc.xdc
