package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   公告表：存储系统公告信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table announcement
 */
public class Announcement {
    /**
     * Database Column Remarks:
     *   公告ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   公告标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   公告类型：1-后台 2-用户端
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   发布人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.publisher_id
     *
     * @mbg.generated
     */
    private Long publisherId;

    /**
     * Database Column Remarks:
     *   推送方式：1-全局弹窗 2-模块查看
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.push_type
     *
     * @mbg.generated
     */
    private Byte pushType;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   公告内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.id
     *
     * @return the value of announcement.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.id
     *
     * @param id the value for announcement.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.title
     *
     * @return the value of announcement.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.title
     *
     * @param title the value for announcement.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.type
     *
     * @return the value of announcement.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.type
     *
     * @param type the value for announcement.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.publisher_id
     *
     * @return the value of announcement.publisher_id
     *
     * @mbg.generated
     */
    public Long getPublisherId() {
        return publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.publisher_id
     *
     * @param publisherId the value for announcement.publisher_id
     *
     * @mbg.generated
     */
    public void setPublisherId(Long publisherId) {
        this.publisherId = publisherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.push_type
     *
     * @return the value of announcement.push_type
     *
     * @mbg.generated
     */
    public Byte getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.push_type
     *
     * @param pushType the value for announcement.push_type
     *
     * @mbg.generated
     */
    public void setPushType(Byte pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.create_time
     *
     * @return the value of announcement.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.create_time
     *
     * @param createTime the value for announcement.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.update_time
     *
     * @return the value of announcement.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.update_time
     *
     * @param updateTime the value for announcement.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.content
     *
     * @return the value of announcement.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.content
     *
     * @param content the value for announcement.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}