package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   审核日志表：记录内容审核的操作日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table audit_log
 */
public class AuditLog {
    /**
     * Database Column Remarks:
     *   审核ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   审核对象类型（举报、博文、挑战）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_log.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     * Database Column Remarks:
     *   审核对象ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_log.target_id
     *
     * @mbg.generated
     */
    private Long targetId;

    /**
     * Database Column Remarks:
     *   审核人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_log.auditor_id
     *
     * @mbg.generated
     */
    private Long auditorId;

    /**
     * Database Column Remarks:
     *   审核结果：0-拒绝 1-通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_log.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   审核原因说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_log.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * Database Column Remarks:
     *   审核时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_log.id
     *
     * @return the value of audit_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_log.id
     *
     * @param id the value for audit_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_log.target_type
     *
     * @return the value of audit_log.target_type
     *
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_log.target_type
     *
     * @param targetType the value for audit_log.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_log.target_id
     *
     * @return the value of audit_log.target_id
     *
     * @mbg.generated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_log.target_id
     *
     * @param targetId the value for audit_log.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_log.auditor_id
     *
     * @return the value of audit_log.auditor_id
     *
     * @mbg.generated
     */
    public Long getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_log.auditor_id
     *
     * @param auditorId the value for audit_log.auditor_id
     *
     * @mbg.generated
     */
    public void setAuditorId(Long auditorId) {
        this.auditorId = auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_log.status
     *
     * @return the value of audit_log.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_log.status
     *
     * @param status the value for audit_log.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_log.reason
     *
     * @return the value of audit_log.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_log.reason
     *
     * @param reason the value for audit_log.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_log.create_time
     *
     * @return the value of audit_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_log.create_time
     *
     * @param createTime the value for audit_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}