package org.example.model.entity;

/**
 * Database Table Remarks:
 *   挑战标签关联表：记录挑战与标签的多对多关系
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table challenge_tag
 */
public class ChallengeTagKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge_tag.challenge_id
     *
     * @mbg.generated
     */
    private Long challengeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge_tag.tag_id
     *
     * @mbg.generated
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge_tag.challenge_id
     *
     * @return the value of challenge_tag.challenge_id
     *
     * @mbg.generated
     */
    public Long getChallengeId() {
        return challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge_tag.challenge_id
     *
     * @param challengeId the value for challenge_tag.challenge_id
     *
     * @mbg.generated
     */
    public void setChallengeId(Long challengeId) {
        this.challengeId = challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge_tag.tag_id
     *
     * @return the value of challenge_tag.tag_id
     *
     * @mbg.generated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge_tag.tag_id
     *
     * @param tagId the value for challenge_tag.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}