package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   挑战主表：存储用户创建的挑战活动信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table challenge
 */
public class Challenge {
    /**
     * Database Column Remarks:
     *   挑战ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   挑战标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   挑战描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   创建者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     * Database Column Remarks:
     *   标志物类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.object_type
     *
     * @mbg.generated
     */
    private String objectType;

    /**
     * Database Column Remarks:
     *   手势类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.gesture_type
     *
     * @mbg.generated
     */
    private String gestureType;

    /**
     * Database Column Remarks:
     *   关联地标名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.landmark_name
     *
     * @mbg.generated
     */
    private String landmarkName;

    /**
     * Database Column Remarks:
     *   有效范围(米)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.radius
     *
     * @mbg.generated
     */
    private Double radius;

    /**
     * Database Column Remarks:
     *   开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     * Database Column Remarks:
     *   结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   参与者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.participants
     *
     * @mbg.generated
     */
    private String participants;

    /**
     * Database Column Remarks:
     *   群组id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.team_id
     *
     * @mbg.generated
     */
    private Long teamId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     * Database Column Remarks:
     *   1表示需要人脸识别，0表示相反
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.need_face_verify
     *
     * @mbg.generated
     */
    private Byte needFaceVerify;

    /**
     * Database Column Remarks:
     *   挑战位置坐标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column challenge.location
     *
     * @mbg.generated
     */
    private byte[] location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.id
     *
     * @return the value of challenge.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.id
     *
     * @param id the value for challenge.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.title
     *
     * @return the value of challenge.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.title
     *
     * @param title the value for challenge.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.description
     *
     * @return the value of challenge.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.description
     *
     * @param description the value for challenge.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.creator_id
     *
     * @return the value of challenge.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.creator_id
     *
     * @param creatorId the value for challenge.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.object_type
     *
     * @return the value of challenge.object_type
     *
     * @mbg.generated
     */
    public String getObjectType() {
        return objectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.object_type
     *
     * @param objectType the value for challenge.object_type
     *
     * @mbg.generated
     */
    public void setObjectType(String objectType) {
        this.objectType = objectType == null ? null : objectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.gesture_type
     *
     * @return the value of challenge.gesture_type
     *
     * @mbg.generated
     */
    public String getGestureType() {
        return gestureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.gesture_type
     *
     * @param gestureType the value for challenge.gesture_type
     *
     * @mbg.generated
     */
    public void setGestureType(String gestureType) {
        this.gestureType = gestureType == null ? null : gestureType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.landmark_name
     *
     * @return the value of challenge.landmark_name
     *
     * @mbg.generated
     */
    public String getLandmarkName() {
        return landmarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.landmark_name
     *
     * @param landmarkName the value for challenge.landmark_name
     *
     * @mbg.generated
     */
    public void setLandmarkName(String landmarkName) {
        this.landmarkName = landmarkName == null ? null : landmarkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.radius
     *
     * @return the value of challenge.radius
     *
     * @mbg.generated
     */
    public Double getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.radius
     *
     * @param radius the value for challenge.radius
     *
     * @mbg.generated
     */
    public void setRadius(Double radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.start_time
     *
     * @return the value of challenge.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.start_time
     *
     * @param startTime the value for challenge.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.end_time
     *
     * @return the value of challenge.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.end_time
     *
     * @param endTime the value for challenge.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.participants
     *
     * @return the value of challenge.participants
     *
     * @mbg.generated
     */
    public String getParticipants() {
        return participants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.participants
     *
     * @param participants the value for challenge.participants
     *
     * @mbg.generated
     */
    public void setParticipants(String participants) {
        this.participants = participants == null ? null : participants.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.team_id
     *
     * @return the value of challenge.team_id
     *
     * @mbg.generated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.team_id
     *
     * @param teamId the value for challenge.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.create_time
     *
     * @return the value of challenge.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.create_time
     *
     * @param createTime the value for challenge.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.images
     *
     * @return the value of challenge.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.images
     *
     * @param images the value for challenge.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.need_face_verify
     *
     * @return the value of challenge.need_face_verify
     *
     * @mbg.generated
     */
    public Byte getNeedFaceVerify() {
        return needFaceVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.need_face_verify
     *
     * @param needFaceVerify the value for challenge.need_face_verify
     *
     * @mbg.generated
     */
    public void setNeedFaceVerify(Byte needFaceVerify) {
        this.needFaceVerify = needFaceVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column challenge.location
     *
     * @return the value of challenge.location
     *
     * @mbg.generated
     */
    public byte[] getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column challenge.location
     *
     * @param location the value for challenge.location
     *
     * @mbg.generated
     */
    public void setLocation(byte[] location) {
        this.location = location;
    }
}