package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户编码表：存储用户多次认证后综合特征编码，可能是一个平均值
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table face_encoding
 */
public class FaceEncoding {
    /**
     * Database Column Remarks:
     *   编码ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_encoding.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_encoding.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_encoding.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_encoding.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   综合特征向量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_encoding.face_encoding
     *
     * @mbg.generated
     */
    private String faceEncoding;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_encoding.id
     *
     * @return the value of face_encoding.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_encoding.id
     *
     * @param id the value for face_encoding.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_encoding.user_id
     *
     * @return the value of face_encoding.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_encoding.user_id
     *
     * @param userId the value for face_encoding.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_encoding.create_time
     *
     * @return the value of face_encoding.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_encoding.create_time
     *
     * @param createTime the value for face_encoding.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_encoding.update_time
     *
     * @return the value of face_encoding.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_encoding.update_time
     *
     * @param updateTime the value for face_encoding.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_encoding.face_encoding
     *
     * @return the value of face_encoding.face_encoding
     *
     * @mbg.generated
     */
    public String getFaceEncoding() {
        return faceEncoding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_encoding.face_encoding
     *
     * @param faceEncoding the value for face_encoding.face_encoding
     *
     * @mbg.generated
     */
    public void setFaceEncoding(String faceEncoding) {
        this.faceEncoding = faceEncoding == null ? null : faceEncoding.trim();
    }
}