package org.example.model.entity;

/**
 * Database Table Remarks:
 *   文件信息表：统一管理所有上传文件的基本信息
 *   存储文件的思路介绍：
 *   ① 在具有图片的数据表（比如博文、挑战、头像）里，其相关的字段修改一下，不存文件名或者url了，用一个数组来存储相关文件在文件系统里的ID，不过用String类型
 *   ② 为什么数组会用String，如何转换：以博文为例
 *       创建时：将选中的图片上传，调用uploads接口，此时在该数据表中生成一条记录，主键id是必有的，这个是BIGINT类型，在java里对应要用Long类型
 *                   有多张图片便有了多个long类型的id，在java里先用数组List去存一下，然后在post数据表生成记录时，对应的image（varchar类型）字段，要存的是List数组转换为String的结果，List有自带的toString方法（相当于存了该list打印出来的结果，                在两端再加上中括号）
 *       访问时：根据post里存的images的String，调用parse方法解析成Long类型的List，根据ID逐个到此表寻找记录，然后在本地存储的文件系统里找到文件，返回给前端
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table file_info
 */
public class FileInfo {
    /**
     * Database Column Remarks:
     *   主键ID，自增
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   存在数据库里的文件的名称
     *   
     *   一般用户上传文件后，要对这个文件名进行处理，常见的就是打时间戳+随机数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   原始文件名（用户上传时的名称）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.origin_name
     *
     * @mbg.generated
     */
    private String originName;

    /**
     * Database Column Remarks:
     *   文件实际存储路径
     *   
     *   可以在根目录或者问问AI，创建一个uploads文件夹
     *   里面可以再分images和videos。
     *   
     *   然后要写一个download的接口，在展示的时候，
     *   从本地的存储文件夹加载出去
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     * Database Column Remarks:
     *   文件扩展名，例如 .png、.pdf
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_suffix
     *
     * @mbg.generated
     */
    private String fileSuffix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.id
     *
     * @return the value of file_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.id
     *
     * @param id the value for file_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_name
     *
     * @return the value of file_info.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_name
     *
     * @param fileName the value for file_info.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.origin_name
     *
     * @return the value of file_info.origin_name
     *
     * @mbg.generated
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.origin_name
     *
     * @param originName the value for file_info.origin_name
     *
     * @mbg.generated
     */
    public void setOriginName(String originName) {
        this.originName = originName == null ? null : originName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_path
     *
     * @return the value of file_info.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_path
     *
     * @param filePath the value for file_info.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_info.file_suffix
     *
     * @return the value of file_info.file_suffix
     *
     * @mbg.generated
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_info.file_suffix
     *
     * @param fileSuffix the value for file_info.file_suffix
     *
     * @mbg.generated
     */
    public void setFileSuffix(String fileSuffix) {
        this.fileSuffix = fileSuffix == null ? null : fileSuffix.trim();
    }
}