package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   关注关系表：记录用户之间的关注关系
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table follow
 */
public class Follow extends FollowKey {
    /**
     * Database Column Remarks:
     *   关注时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.create_time
     *
     * @return the value of follow.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.create_time
     *
     * @param createTime the value for follow.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}