package org.example.model.entity;

/**
 * Database Table Remarks:
 *   关注关系表：记录用户之间的关注关系
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table follow
 */
public class FollowKey {
    /**
     * Database Column Remarks:
     *   关注者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.follower_id
     *
     * @mbg.generated
     */
    private Long followerId;

    /**
     * Database Column Remarks:
     *   被关注者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.followee_id
     *
     * @mbg.generated
     */
    private Long followeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.follower_id
     *
     * @return the value of follow.follower_id
     *
     * @mbg.generated
     */
    public Long getFollowerId() {
        return followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.follower_id
     *
     * @param followerId the value for follow.follower_id
     *
     * @mbg.generated
     */
    public void setFollowerId(Long followerId) {
        this.followerId = followerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.followee_id
     *
     * @return the value of follow.followee_id
     *
     * @mbg.generated
     */
    public Long getFolloweeId() {
        return followeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.followee_id
     *
     * @param followeeId the value for follow.followee_id
     *
     * @mbg.generated
     */
    public void setFolloweeId(Long followeeId) {
        this.followeeId = followeeId;
    }
}