package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   转发表：记录用户转发内容的信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table forward
 */
public class Forward {
    /**
     * Database Column Remarks:
     *   转发ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   转发用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   转发对象类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     * Database Column Remarks:
     *   转发对象ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.target_id
     *
     * @mbg.generated
     */
    private Long targetId;

    /**
     * Database Column Remarks:
     *   转发时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   转发评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forward.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.id
     *
     * @return the value of forward.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.id
     *
     * @param id the value for forward.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.user_id
     *
     * @return the value of forward.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.user_id
     *
     * @param userId the value for forward.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.target_type
     *
     * @return the value of forward.target_type
     *
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.target_type
     *
     * @param targetType the value for forward.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.target_id
     *
     * @return the value of forward.target_id
     *
     * @mbg.generated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.target_id
     *
     * @param targetId the value for forward.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.create_time
     *
     * @return the value of forward.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.create_time
     *
     * @param createTime the value for forward.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forward.comment
     *
     * @return the value of forward.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forward.comment
     *
     * @param comment the value for forward.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}