package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   点赞记录表：记录用户点赞行为
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table like
 */
public class Like {
    /**
     * Database Column Remarks:
     *   点赞ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   点赞用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   点赞对象类型：1-博文 2-评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     * Database Column Remarks:
     *   点赞对象ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.target_id
     *
     * @mbg.generated
     */
    private Long targetId;

    /**
     * Database Column Remarks:
     *   点赞时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.id
     *
     * @return the value of like.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.id
     *
     * @param id the value for like.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.user_id
     *
     * @return the value of like.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.user_id
     *
     * @param userId the value for like.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.target_type
     *
     * @return the value of like.target_type
     *
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.target_type
     *
     * @param targetType the value for like.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.target_id
     *
     * @return the value of like.target_id
     *
     * @mbg.generated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.target_id
     *
     * @param targetId the value for like.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like.create_time
     *
     * @return the value of like.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like.create_time
     *
     * @param createTime the value for like.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}