package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   通知表：存储系统通知信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table notification
 */
public class Notification {
    /**
     * Database Column Remarks:
     *   通知ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   发送者ID(系统通知为也为一个用户)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.sender_id
     *
     * @mbg.generated
     */
    private Long senderId;

    /**
     * Database Column Remarks:
     *   接收者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.receiver_id
     *
     * @mbg.generated
     */
    private Long receiverId;

    /**
     * Database Column Remarks:
     *   通知类型：1-评论 2-点赞 3-系统
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   通知内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   是否已读：0-未读 1-已读
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.is_read
     *
     * @mbg.generated
     */
    private Boolean isRead;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   对应类型的id，如类型是1，id就代表是评论id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.type_id
     *
     * @mbg.generated
     */
    private Long typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.sender_id
     *
     * @return the value of notification.sender_id
     *
     * @mbg.generated
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.sender_id
     *
     * @param senderId the value for notification.sender_id
     *
     * @mbg.generated
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.receiver_id
     *
     * @return the value of notification.receiver_id
     *
     * @mbg.generated
     */
    public Long getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.receiver_id
     *
     * @param receiverId the value for notification.receiver_id
     *
     * @mbg.generated
     */
    public void setReceiverId(Long receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.type
     *
     * @return the value of notification.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.type
     *
     * @param type the value for notification.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.content
     *
     * @return the value of notification.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.content
     *
     * @param content the value for notification.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.is_read
     *
     * @return the value of notification.is_read
     *
     * @mbg.generated
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.is_read
     *
     * @param isRead the value for notification.is_read
     *
     * @mbg.generated
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.create_time
     *
     * @return the value of notification.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.create_time
     *
     * @param createTime the value for notification.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.type_id
     *
     * @return the value of notification.type_id
     *
     * @mbg.generated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.type_id
     *
     * @param typeId the value for notification.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }
}