package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   操作日志表：记录用户的操作日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table operation_log
 */
public class OperationLog {
    /**
     * Database Column Remarks:
     *   日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   操作者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   操作对象的类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.module
     *
     * @mbg.generated
     */
    private String module;

    /**
     * Database Column Remarks:
     *   操作类型（增删改）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     * Database Column Remarks:
     *   操作对象ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.target_id
     *
     * @mbg.generated
     */
    private String targetId;

    /**
     * Database Column Remarks:
     *   操作备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.id
     *
     * @return the value of operation_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.id
     *
     * @param id the value for operation_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.user_id
     *
     * @return the value of operation_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.user_id
     *
     * @param userId the value for operation_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.module
     *
     * @return the value of operation_log.module
     *
     * @mbg.generated
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.module
     *
     * @param module the value for operation_log.module
     *
     * @mbg.generated
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.action
     *
     * @return the value of operation_log.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.action
     *
     * @param action the value for operation_log.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.target_id
     *
     * @return the value of operation_log.target_id
     *
     * @mbg.generated
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.target_id
     *
     * @param targetId the value for operation_log.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId == null ? null : targetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.detail
     *
     * @return the value of operation_log.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.detail
     *
     * @param detail the value for operation_log.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.create_time
     *
     * @return the value of operation_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.create_time
     *
     * @param createTime the value for operation_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}