package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   挑战参与记录表：记录用户参与挑战的情况
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table participation
 */
public class Participation {
    /**
     * Database Column Remarks:
     *   参与记录ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   参与用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   挑战ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.challenge_id
     *
     * @mbg.generated
     */
    private Long challengeId;

    /**
     * Database Column Remarks:
     *   完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.complete_time
     *
     * @mbg.generated
     */
    private Date completeTime;

    /**
     * Database Column Remarks:
     *   状态:完成状态，0为失败，1为完成，2为参加
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.complete_state
     *
     * @mbg.generated
     */
    private Byte completeState;

    /**
     * Database Column Remarks:
     *   完成证据(JSON格式，可以存储比较多的信息，比如上传的图片路径...)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation.evidence
     *
     * @mbg.generated
     */
    private String evidence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.id
     *
     * @return the value of participation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.id
     *
     * @param id the value for participation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.user_id
     *
     * @return the value of participation.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.user_id
     *
     * @param userId the value for participation.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.challenge_id
     *
     * @return the value of participation.challenge_id
     *
     * @mbg.generated
     */
    public Long getChallengeId() {
        return challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.challenge_id
     *
     * @param challengeId the value for participation.challenge_id
     *
     * @mbg.generated
     */
    public void setChallengeId(Long challengeId) {
        this.challengeId = challengeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.complete_time
     *
     * @return the value of participation.complete_time
     *
     * @mbg.generated
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.complete_time
     *
     * @param completeTime the value for participation.complete_time
     *
     * @mbg.generated
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.complete_state
     *
     * @return the value of participation.complete_state
     *
     * @mbg.generated
     */
    public Byte getCompleteState() {
        return completeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.complete_state
     *
     * @param completeState the value for participation.complete_state
     *
     * @mbg.generated
     */
    public void setCompleteState(Byte completeState) {
        this.completeState = completeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation.evidence
     *
     * @return the value of participation.evidence
     *
     * @mbg.generated
     */
    public String getEvidence() {
        return evidence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation.evidence
     *
     * @param evidence the value for participation.evidence
     *
     * @mbg.generated
     */
    public void setEvidence(String evidence) {
        this.evidence = evidence == null ? null : evidence.trim();
    }
}