package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   博文表：存储用户发布的动态内容
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table post
 */
public class Post {
    /**
     * Database Column Remarks:
     *   博文ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   作者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   博文标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   图片文件的id数组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     * Database Column Remarks:
     *   视频文件的id数组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.videos
     *
     * @mbg.generated
     */
    private String videos;

    /**
     * Database Column Remarks:
     *   是否公开：0-私密 1-公开
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.is_public
     *
     * @mbg.generated
     */
    private Boolean isPublic;

    /**
     * Database Column Remarks:
     *   浏览次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.view_count
     *
     * @mbg.generated
     */
    private Integer viewCount;

    /**
     * Database Column Remarks:
     *   点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.like_count
     *
     * @mbg.generated
     */
    private Integer likeCount;

    /**
     * Database Column Remarks:
     *   评论数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.comment_count
     *
     * @mbg.generated
     */
    private Integer commentCount;

    /**
     * Database Column Remarks:
     *   审核状态：0-待审核 1-已通过 2-未通过
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.landmark_name
     *
     * @mbg.generated
     */
    private String landmarkName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.id
     *
     * @return the value of post.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.id
     *
     * @param id the value for post.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.user_id
     *
     * @return the value of post.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.user_id
     *
     * @param userId the value for post.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.images
     *
     * @return the value of post.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.images
     *
     * @param images the value for post.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.videos
     *
     * @return the value of post.videos
     *
     * @mbg.generated
     */
    public String getVideos() {
        return videos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.videos
     *
     * @param videos the value for post.videos
     *
     * @mbg.generated
     */
    public void setVideos(String videos) {
        this.videos = videos == null ? null : videos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.is_public
     *
     * @return the value of post.is_public
     *
     * @mbg.generated
     */
    public Boolean getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.is_public
     *
     * @param isPublic the value for post.is_public
     *
     * @mbg.generated
     */
    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.view_count
     *
     * @return the value of post.view_count
     *
     * @mbg.generated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.view_count
     *
     * @param viewCount the value for post.view_count
     *
     * @mbg.generated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.like_count
     *
     * @return the value of post.like_count
     *
     * @mbg.generated
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.like_count
     *
     * @param likeCount the value for post.like_count
     *
     * @mbg.generated
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.comment_count
     *
     * @return the value of post.comment_count
     *
     * @mbg.generated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.comment_count
     *
     * @param commentCount the value for post.comment_count
     *
     * @mbg.generated
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.status
     *
     * @return the value of post.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.status
     *
     * @param status the value for post.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.create_time
     *
     * @return the value of post.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.create_time
     *
     * @param createTime the value for post.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.landmark_name
     *
     * @return the value of post.landmark_name
     *
     * @mbg.generated
     */
    public String getLandmarkName() {
        return landmarkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.landmark_name
     *
     * @param landmarkName the value for post.landmark_name
     *
     * @mbg.generated
     */
    public void setLandmarkName(String landmarkName) {
        this.landmarkName = landmarkName == null ? null : landmarkName.trim();
    }
}