package org.example.model.entity;

/**
 * Database Table Remarks:
 *   博文表：存储用户发布的动态内容
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table post
 */
public class PostWithBLOBs extends Post {
    /**
     * Database Column Remarks:
     *   博文内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   发布位置坐标
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.location
     *
     * @mbg.generated
     */
    private byte[] location;

    private String landmark_name;

    public String getLandmark_name() {
        return landmark_name;
    }

    public void setLandmark_name(String landmark_name) {
        this.landmark_name = landmark_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.location
     *
     * @return the value of post.location
     *
     * @mbg.generated
     */
    public byte[] getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.location
     *
     * @param location the value for post.location
     *
     * @mbg.generated
     */
    public void setLocation(byte[] location) {
        this.location = location;
    }
}