package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   举报记录表：记录用户举报内容的信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table report
 */
public class Report {
    /**
     * Database Column Remarks:
     *   举报ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   举报对象类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.target_type
     *
     * @mbg.generated
     */
    private String targetType;

    /**
     * Database Column Remarks:
     *   举报对象ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.target_id
     *
     * @mbg.generated
     */
    private Long targetId;

    /**
     * Database Column Remarks:
     *   举报原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * Database Column Remarks:
     *   举报人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reporter_id
     *
     * @mbg.generated
     */
    private Long reporterId;

    /**
     * Database Column Remarks:
     *   处理状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   处理结果说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.handle_result
     *
     * @mbg.generated
     */
    private String handleResult;

    /**
     * Database Column Remarks:
     *   举报时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.target_type
     *
     * @return the value of report.target_type
     *
     * @mbg.generated
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.target_type
     *
     * @param targetType the value for report.target_type
     *
     * @mbg.generated
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType == null ? null : targetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.target_id
     *
     * @return the value of report.target_id
     *
     * @mbg.generated
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.target_id
     *
     * @param targetId the value for report.target_id
     *
     * @mbg.generated
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reason
     *
     * @return the value of report.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reason
     *
     * @param reason the value for report.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reporter_id
     *
     * @return the value of report.reporter_id
     *
     * @mbg.generated
     */
    public Long getReporterId() {
        return reporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reporter_id
     *
     * @param reporterId the value for report.reporter_id
     *
     * @mbg.generated
     */
    public void setReporterId(Long reporterId) {
        this.reporterId = reporterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.status
     *
     * @return the value of report.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.status
     *
     * @param status the value for report.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.handle_result
     *
     * @return the value of report.handle_result
     *
     * @mbg.generated
     */
    public String getHandleResult() {
        return handleResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.handle_result
     *
     * @param handleResult the value for report.handle_result
     *
     * @mbg.generated
     */
    public void setHandleResult(String handleResult) {
        this.handleResult = handleResult == null ? null : handleResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.create_time
     *
     * @return the value of report.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.create_time
     *
     * @param createTime the value for report.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}