package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   验证码表：存储短信/邮箱验证码信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_code
 */
public class SmsCode {
    /**
     * Database Column Remarks:
     *   验证码ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   手机号或邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.identifier
     *
     * @mbg.generated
     */
    private String identifier;

    /**
     * Database Column Remarks:
     *   验证码类型：1-邮箱 2-手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   验证码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   过期时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.expire_time
     *
     * @mbg.generated
     */
    private Date expireTime;

    /**
     * Database Column Remarks:
     *   状态：0-未使用 1-已使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_code.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.id
     *
     * @return the value of sms_code.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.id
     *
     * @param id the value for sms_code.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.identifier
     *
     * @return the value of sms_code.identifier
     *
     * @mbg.generated
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.identifier
     *
     * @param identifier the value for sms_code.identifier
     *
     * @mbg.generated
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.type
     *
     * @return the value of sms_code.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.type
     *
     * @param type the value for sms_code.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.code
     *
     * @return the value of sms_code.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.code
     *
     * @param code the value for sms_code.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.expire_time
     *
     * @return the value of sms_code.expire_time
     *
     * @mbg.generated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.expire_time
     *
     * @param expireTime the value for sms_code.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_code.status
     *
     * @return the value of sms_code.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_code.status
     *
     * @param status the value for sms_code.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}