package org.example.model.entity;

/**
 * Database Table Remarks:
 *   群组成员表：记录群组成员及其角色信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team_member
 */
public class TeamMemberKey {
    /**
     * Database Column Remarks:
     *   群组ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.team_id
     *
     * @mbg.generated
     */
    private Long teamId;

    /**
     * Database Column Remarks:
     *   成员用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_member.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.team_id
     *
     * @return the value of team_member.team_id
     *
     * @mbg.generated
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.team_id
     *
     * @param teamId the value for team_member.team_id
     *
     * @mbg.generated
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_member.user_id
     *
     * @return the value of team_member.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_member.user_id
     *
     * @param userId the value for team_member.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}