package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   群组表：存储用户创建的群组信息
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table team
 */
public class Team {
    /**
     * Database Column Remarks:
     *   群组ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   群组名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   群组LOGO URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.logo
     *
     * @mbg.generated
     */
    private String logo;

    /**
     * Database Column Remarks:
     *   创建者用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.creator_id
     *
     * @mbg.generated
     */
    private Long creatorId;

    /**
     * Database Column Remarks:
     *   最大成员数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.max_members
     *
     * @mbg.generated
     */
    private Integer maxMembers;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.id
     *
     * @return the value of team.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.id
     *
     * @param id the value for team.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.name
     *
     * @return the value of team.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.name
     *
     * @param name the value for team.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.logo
     *
     * @return the value of team.logo
     *
     * @mbg.generated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.logo
     *
     * @param logo the value for team.logo
     *
     * @mbg.generated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.creator_id
     *
     * @return the value of team.creator_id
     *
     * @mbg.generated
     */
    public Long getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.creator_id
     *
     * @param creatorId the value for team.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(Long creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.max_members
     *
     * @return the value of team.max_members
     *
     * @mbg.generated
     */
    public Integer getMaxMembers() {
        return maxMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.max_members
     *
     * @param maxMembers the value for team.max_members
     *
     * @mbg.generated
     */
    public void setMaxMembers(Integer maxMembers) {
        this.maxMembers = maxMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.create_time
     *
     * @return the value of team.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.create_time
     *
     * @param createTime the value for team.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}