package org.example.model.entity;

/**
 * Database Table Remarks:
 *   用户标签关联表：记录用户与标签的多对多关系
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_tag
 */
public class UserTagKey {
    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   标签ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_tag.tag_id
     *
     * @mbg.generated
     */
    private Long tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.user_id
     *
     * @return the value of user_tag.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.user_id
     *
     * @param userId the value for user_tag.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_tag.tag_id
     *
     * @return the value of user_tag.tag_id
     *
     * @mbg.generated
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_tag.tag_id
     *
     * @param tagId the value for user_tag.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }
}