package org.example.model.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户资料扩展表：存储用户的详细个人资料和设置
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_profile
 */
public class UserProfile {
    /**
     * Database Column Remarks:
     *   用户ID，关联user表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   性别：男/女/null
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     * Database Column Remarks:
     *   出生日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   个人简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.bio
     *
     * @mbg.generated
     */
    private String bio;

    /**
     * Database Column Remarks:
     *   地理位置
     *   例：广东广州
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * Database Column Remarks:
     *   用户设置(JSON格式)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_profile.settings
     *
     * @mbg.generated
     */
    private String settings;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.user_id
     *
     * @return the value of user_profile.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.user_id
     *
     * @param userId the value for user_profile.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.gender
     *
     * @return the value of user_profile.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.gender
     *
     * @param gender the value for user_profile.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.birthday
     *
     * @return the value of user_profile.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.birthday
     *
     * @param birthday the value for user_profile.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.bio
     *
     * @return the value of user_profile.bio
     *
     * @mbg.generated
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.bio
     *
     * @param bio the value for user_profile.bio
     *
     * @mbg.generated
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.location
     *
     * @return the value of user_profile.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.location
     *
     * @param location the value for user_profile.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_profile.settings
     *
     * @return the value of user_profile.settings
     *
     * @mbg.generated
     */
    public String getSettings() {
        return settings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_profile.settings
     *
     * @param settings the value for user_profile.settings
     *
     * @mbg.generated
     */
    public void setSettings(String settings) {
        this.settings = settings == null ? null : settings.trim();
    }
}