# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/sources/xup_and_basys3.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_xup_and2_0_0/system_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xup_and2_0_0 || ORIG_REF_NAME==system_xup_and2_0_0}]

# IP: bd/system/ip/system_xup_and_vector_0_0/system_xup_and_vector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xup_and_vector_0_0 || ORIG_REF_NAME==system_xup_and_vector_0_0}]

# XDC: bd/system/system_ooc.xdc
