# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.cache/wt [current_project]
set_property parent.project_path C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths C:/XILINX/labtwo/xup_lib [current_project]
add_files C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.srcs/sources_1/bd/system/hdl/system_wrapper.v
read_xdc C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.srcs/constrs_1/imports/sources/xup_and_basys3.xdc
set_property used_in_implementation false [get_files C:/XILINX/labtwo/xup_and_test/xup_and_test/xup_and_test.srcs/constrs_1/imports/sources/xup_and_basys3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file system_wrapper.hwdef }
synth_design -top system_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
