#Basys3
set_property PACKAGE_PIN V17 [get_ports SW0]
set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property PACKAGE_PIN V16 [get_ports SW1]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property PACKAGE_PIN W16 [get_ports SW2]
set_property IOSTANDARD LVCMOS33 [get_ports SW2]
set_property PACKAGE_PIN W17 [get_ports SW3]
set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property PACKAGE_PIN W15 [get_ports SW4]
set_property IOSTANDARD LVCMOS33 [get_ports SW4]
set_property PACKAGE_PIN V15 [get_ports SW5]
set_property IOSTANDARD LVCMOS33 [get_ports SW5]
set_property PACKAGE_PIN W14 [get_ports SW6]
set_property IOSTANDARD LVCMOS33 [get_ports SW6]

set_property PACKAGE_PIN U16 [get_ports LD0]
set_property IOSTANDARD LVCMOS33 [get_ports LD0]
set_property PACKAGE_PIN E19 [get_ports LD1]
set_property IOSTANDARD LVCMOS33 [get_ports LD1]
set_property PACKAGE_PIN U19 [get_ports LD2]
set_property IOSTANDARD LVCMOS33 [get_ports LD2]
set_property PACKAGE_PIN V19 [get_ports LD3]
set_property IOSTANDARD LVCMOS33 [get_ports LD3]
set_property PACKAGE_PIN W18 [get_ports LD4]
set_property IOSTANDARD LVCMOS33 [get_ports LD4]
set_property PACKAGE_PIN U15 [get_ports LD5]
set_property IOSTANDARD LVCMOS33 [get_ports LD5]
set_property PACKAGE_PIN U14 [get_ports LD6]
set_property IOSTANDARD LVCMOS33 [get_ports LD6]



set_property DONT_TOUCH true [get_cells design_1_i]
set_property DONT_TOUCH true [get_cells design_1_i/xup_and2_0]
set_property DONT_TOUCH true [get_cells design_1_i/xup_and2_1]
set_property DONT_TOUCH true [get_cells design_1_i/xup_inv_0]
set_property DONT_TOUCH true [get_cells design_1_i/xup_inv_1]
set_property DONT_TOUCH true [get_cells design_1_i/xup_or2_0]
set_property IOSTANDARD LVCMOS33 [get_ports LD7]
set_property PACKAGE_PIN V14 [get_ports LD7]
set_property PACKAGE_PIN W13 [get_ports SW7]
set_property IOSTANDARD LVCMOS33 [get_ports SW7]

