package org.example.mapper;

import org.apache.ibatis.annotations.Param;
import org.example.model.entity.Announcement;
import org.springframework.stereotype.Repository;
import tk.mybatis.mapper.common.BaseMapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

@Repository
public interface AnnouncementMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated
     */
    int insert(Announcement row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated
     */
    int insertSelective(Announcement row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated
     */
    Announcement selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Announcement row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Announcement row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated
     */


    int updateByPrimaryKey(Announcement row);
    List<Announcement> selectAnnouncements(@Param("params") Map<String, Object> params);
    List<Announcement> selectAnnouncementsmore(@Param("params") Map<String, Object> params);


    List<Announcement> selectAnnouncementsByConditions(
            @Param("title") String title,
            @Param("type") Integer type,
            @Param("startTime") Date startTime,
            @Param("endTime") Date endTime);





    List<Announcement> selectAnnouncements_1();
    // TOTORO新增方法：根据公告ID列表查询公告
    List<Announcement> selectByIds(@Param("ids") List<Long> ids);
}