package org.example.mapper;

import org.example.model.entity.Follow;
import org.example.model.entity.FollowKey;

public interface FollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FollowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int insert(Follow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int insertSelective(Follow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    Follow selectByPrimaryKey(FollowKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Follow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Follow row);
}