package org.example.mapper;

import org.example.model.entity.PostTagKey;

public interface PostTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(PostTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated
     */
    int insert(PostTagKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_tag
     *
     * @mbg.generated
     */
    int insertSelective(PostTagKey row);
}