package org.example.mapper;

import org.example.model.entity.SmsCode;

public interface SmsCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    int insert(SmsCode row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    int insertSelective(SmsCode row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    SmsCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsCode row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsCode row);
}