package org.example.mapper;

import org.example.model.entity.UserTagKey;

public interface UserTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UserTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbg.generated
     */
    int insert(UserTagKey row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbg.generated
     */
    int insertSelective(UserTagKey row);
}