# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/XILINX/labthree/tutorial/tutorial.cache/wt [current_project]
set_property parent.project_path C:/XILINX/labthree/tutorial/tutorial.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/XILINX/labthree/tutorial/tutorial.srcs/sources_1/imports/tutorial_/tutorial.v
read_xdc C:/XILINX/labthree/tutorial/tutorial.srcs/constrs_1/imports/tutorial_/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/XILINX/labthree/tutorial/tutorial.srcs/constrs_1/imports/tutorial_/Basys3_Master.xdc]

catch { write_hwdef -file tutorial.hwdef }
synth_design -top tutorial -part xc7a35tcpg236-1
write_checkpoint -noxdef tutorial.dcp
catch { report_utilization -file tutorial_utilization_synth.rpt -pb tutorial_utilization_synth.pb }
