# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/XILINX/lab4/4_2_/moore/moore.cache/wt [current_project]
set_property parent.project_path C:/XILINX/lab4/4_2_/moore/moore.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv C:/XILINX/lab4/4_2_/moore/moore.srcs/sources_1/imports/4_2_/moore.sv
read_xdc C:/XILINX/lab4/4_2_/moore/moore.srcs/constrs_1/imports/4_2moore/moore.xdc
set_property used_in_implementation false [get_files C:/XILINX/lab4/4_2_/moore/moore.srcs/constrs_1/imports/4_2moore/moore.xdc]

catch { write_hwdef -file div3.hwdef }
synth_design -top div3 -part xc7a35tcpg236-1
write_checkpoint -noxdef div3.dcp
catch { report_utilization -file div3_utilization_synth.rpt -pb div3_utilization_synth.pb }
